### PR TITLE
Fix a false positive for `RSpec/MatchArray` when `match_array` with an empty array

### PR DESCRIPTION
**Pull request by ydah**
Fix: #1591

______________________________________________________________________

Before submitting the PR make sure the following are checked:

- [x] Feature branch is up-to-date with `master` (if not - rebase it).
- [x] Squashed related commits together.
- [x] Added tests.
- [-] Updated documentation.
- [x] Added an entry to the `CHANGELOG.md` if the new code introduces user-observable changes.
- [x] The build (`bundle exec rake`) passes (be sure to run this locally, since it may produce updated documentation that you will need to commit).

### CODE REVIEW

**Comment by bquorning** [comment]
I wonder if we should change `match_array([])` into `eq([])`, of if that is too much of a change?

**Comment by ydah** [comment]
> I wonder if we should change `match_array([])` into `eq([])`, of if that is too much of a change?

I would suggest letting the next cop make that change. What do you think?
- https://github.com/rubocop/rubocop-rspec/pull/1594

**Comment by CKolkey** [comment]
For what it's worth, when accounting for this cop yesterday, the change I made was from `match_array([])` to `eq([])`.

**Comment by ydah** [comment]
We have determined that the https://github.com/rubocop/rubocop-rspec/pull/1597 way is best and will close this.

**Pull request closed without merging**
