### PR TITLE
Bump version to 2.13.2

### PR DESCRIPTION
**Pull request by bquorning**
A couple of bugfixes ready to go out.

---

Before submitting the PR make sure the following are checked:

* [ ] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [ ] Added tests.
* [ ] Updated documentation.
* [x] Added an entry to the `CHANGELOG.md` if the new code introduces user-observable changes.
* [x] The build (`bundle exec rake`) passes (be sure to run this locally, since it may produce updated documentation that you will need to commit).

### CODE REVIEW

**Comment by bquorning** [comment]
Perhaps we should wait for #1391?

**Comment by Darhazer** [comment]
That's what I was going to suggest

**Comment by Darhazer** [comment]
#1391 has been merged :shipit:

**Comment by bquorning** [comment]
@ydah, @Darhazer This is ready for review.

**Review by nijikon — APPROVED** [review]

**Review by ydah — APPROVED** [review]
🚀

**Review by Darhazer — APPROVED** [review]
Thank you

**Pull request merged**
