### PR TITLE
Enable `Style/RequireOrder` cop

### PR DESCRIPTION
**Pull request by r7kamura**
By enabling the `Style/RequireOrder` cop added in rubocop 1.40.0, you no longer need to check it yourself in spec/project/project_requires_spec.rb. In addition, it makes the order consistent in other files as well.

Note that if you run it with older than rubocop 1.40.0, it will fail because this Cop does not yet exist.
______________________________________________________________________

Before submitting the PR make sure the following are checked:

- [x] Feature branch is up-to-date with `master` (if not - rebase it).
- [x] Squashed related commits together.
- [ ] Added tests.
- [ ] Updated documentation.
- [ ] Added an entry to the `CHANGELOG.md` if the new code introduces user-observable changes.
- [ ] The build (`bundle exec rake`) passes (be sure to run this locally, since it may produce updated documentation that you will need to commit).

### CODE REVIEW

**Comment by r7kamura** [comment]
See https://github.com/rubocop/rubocop-rspec/pull/1510 first for the CI failure.

**Review by pirj — APPROVED** [review]
Thank you!

**Comment by pirj** [comment]
Now getting back to the topic of committing `Gemfile.lock` to the repository that you've brought up earlier.

**Comment by pirj** [comment]
Thank you, @r7kamura !

**Pull request merged**
