### PR TITLE
Add new `RSpec/BeNil` cop

### LINKED ISSUE #244: Identity comparison vs. value comparison
Perhaps mostly a pet peeve, but I would like to enforce the following styles:

1. Use `be_nil` instead of `be(nil)` or `eq(nil)`.
2. Use `be(true)` instead of `eq(true)`.
3. Use `be(false)` instead of `eq(false)`.

Maybe also

4. Use `to be_nil` instead of `not_to be`.
5. Use `not_to be_nil` instead of `to be`.

### PR DESCRIPTION
**Pull request by bquorning**
Check that `be_nil` is used instead of `be(nil)`.

RSpec has a built-in `be_nil` matcher specifically for expecting `nil`. For consistent specs, we recommend using that instead of `be(nil)`.

Partially fixes #244.

---

Before submitting the PR make sure the following are checked:

* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [ ] Squashed related commits together.
* [x] Added tests.
* [x] Updated documentation.
* [x] Added an entry to the `CHANGELOG.md` if the new code introduces user-observable changes.
* [x] The build (`bundle exec rake`) passes (be sure to run this locally, since it may produce updated documentation that you will need to commit).

If you have created a new cop:

* [x] Added the new cop to `config/default.yml`.
* [x] The cop is configured as `Enabled: pending` in `config/default.yml`.
* [x] The cop documents examples of good and bad code.
* [x] The tests assert both that bad code is reported and that good code is not reported.
* [x] Set `VersionAdded` in `default/config.yml` to the next minor version.

If you have modified an existing cop's configuration options:

* [ ] Set `VersionChanged` in `config/default.yml` to the next major version.

### CODE REVIEW

**Review by Darhazer — APPROVED** [review]

**Review by pirj — APPROVED** [review]
Looks good, thank you!

**Comment by marcandre** [comment]
Note that it's not 100% safe.

```
expect(OpenStruct.new(nil?: true)).to be_nil # => pass
expect(OpenStruct.new(nil?: true)).to be nil # => fail
```

More importantly, I see absolutely no reason to prefer `be_nil` to `be nil`. The later is stricter, simpler and requires less knowledge of `rspec`.

**Comment by pirj** [comment]
We couldn't [figure out a real example](https://github.com/rubocop/rubocop-rspec/issues/244#issuecomment-1048556473).

**Comment by bquorning** [comment]
> I see absolutely no reason to prefer `be_nil` to `be nil`. The later is stricter, simpler and requires less knowledge of `rspec`.

Well, that _is_ true 😅 Should we consider making the cop configurable to users can enforce either one style or the other?

**Pull request merged**
