### PR TITLE
Pass range as a positional arg

### PR DESCRIPTION
**Pull request by pirj**
As introduced in https://github.com/rubocop/rubocop/pull/10748

Since RuboCop with this PR wasn't released yet, the CI will be red.

---

Before submitting the PR make sure the following are checked:

* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [-] Added tests.
* [-] Updated documentation.
* [-] Added an entry to the `CHANGELOG.md` if the new code introduces user-observable changes.
* [x] The build (`bundle exec rake`) passes (be sure to run this locally, since it may produce updated documentation that you will need to commit). - locally, against the `rubocop` PR

### CODE REVIEW

**Review by bquorning — APPROVED** [review]

**Comment by bquorning** [comment]
I think this PR needs a mention in the changelog, just like #1181.

We should also ask:
1. Do we want to incorporate more newly added RuboCop features, when we do the requirement bump anyway?
2. Do we want to do the requirement just now, or is this a PR that we should wait a month before merging/releasing?

**Comment by pirj** [comment]
[Released in RuboCop 1.31.0](https://github.com/rubocop/rubocop/releases/tag/v1.31.0).

**Comment by pirj** [comment]
> Do we want to incorporate more newly added RuboCop features, when we do the requirement bump anyway?

Yes. But I'm not aware of any.

> wait a month before merging/releasing

Why? Not to force users into `rubocop` 1.31.0 and to wait for 1.31.1 that would probably include bugfixes?

**Comment by bquorning** [comment]
> Why? Not to force users into `rubocop` 1.31.0 and to wait for 1.31.1 that would probably include bugfixes?

🤷🏼 I guess there’s no good reason to wait 😄

**Pull request merged**
