### PR TITLE
Add rake tasks for alternative way to specify Changelog entries

### PR DESCRIPTION
**Pull request by ydah**
Follow: https://github.com/rubocop/rubocop/pull/8930 and https://github.com/rubocop/rubocop-rails/pull/496

______________________________________________________________________

Before submitting the PR make sure the following are checked:

- [x] Feature branch is up-to-date with `master` (if not - rebase it).
- [x] Squashed related commits together.
- [ ] Added tests.
- [-] Updated documentation.
- [-] Added an entry to the `CHANGELOG.md` if the new code introduces user-observable changes.
- [x] The build (`bundle exec rake`) passes (be sure to run this locally, since it may produce updated documentation that you will need to commit).

### CODE REVIEW

**Comment by pirj** [comment]
I feel severe reluctance to this approach. We don't have that many updates, and rebasing and fixing the changelog doesn't feel to be a significant overhead. Contrary to a strict suggested format.

The changelog file in between the releases is also now scattered across several files.

I hope that with splitting the repo, the surface will reduce as well.

During a few recent minor releases, we were doing a good job of communicating on PRs and merged them quickly.

**Comment by ydah** [comment]
- https://github.com/rubocop/rubocop-rspec/discussions/1417
It was spoken about here, so we worked on it. However, it is true that we don't get that many PRs sent to us on a daily basis now, so it may just be overhead.
Basically this approach is the same as rubocop and rubocop-rspec, so we can always come back to this.

**Comment by pirj** [comment]
My apologies. I refreshed my memory by reading #1417 and now recall I gave in, provided all the arguments, but kept my previous opinion.
Thanks for this PR.
I would personally postpone the decision until the need arises.

**Comment by ydah** [comment]
We can resume this again, so let's Close this PR.

**Pull request closed without merging**
