### PR TITLE
Patch release (v2.17.1)

### PR DESCRIPTION
**Pull request by bquorning**
Releasing v2.17.1 with the recent patches by @ydah but _without_ #1519 from @pirj (which will be released as v2.18.0 soon after).

The v2.17.1 release will be cut from commit f510f1a0aaec4d12b801d769a8d2106c8f782259.

### CODE REVIEW

**Review by pirj — APPROVED** [review]
Thank you!

**Comment by koic** [comment]
Nits: The branch name `patch-release` seems generic. How about creating a branch called `2-17-stable` and cherry-picking it?

```console
% git checkout v2.17.0
% git checkout -b 2-17-stable
% git cherry-pick 3799e63e1fb5941e4f6a72f0f6d03be4aa5d2c37 # https://github.com/rubocop/rubocop-rspec/pull/1555
% git cherry-pick  5113d6f96ad536979710b361e3d6c101daa84da6 # https://github.com/rubocop/rubocop-rspec/pull/1554
% # Commit "Patch release (v2.17.1)"
% # Release
```

This branching strategy is used in rails/rails and ruby/ruby repos.

**Comment by pirj** [comment]
Our release timeline is linear, unlike Ruby or Rails'. We don't intend to make any further 2.17.x releases after 2.18 is released. With that in mind, 2.17-stable seems unnecessary.

**Comment by bquorning** [comment]
Yes, `patch-release` is intended as a throw-away branch.

**Comment by koic** [comment]
I get it! Thank you for the explanation and the bug fix release!

**Pull request merged**
