### PR TITLE
Bump version to v2.23.0

### PR DESCRIPTION
**Pull request by bquorning**
It has been a couple of months. Are we ready for the next release? Are there some more pull requests we need to get merged first?

### CODE REVIEW

**Comment by ydah** [comment]
We would like to include the next revision.
- https://github.com/rubocop/rubocop-rspec/pull/1662

These PRs are not urgent as they are an addition to the cop:
- https://github.com/rubocop/rubocop-rspec/pull/1665
- https://github.com/rubocop/rubocop-rspec/pull/1666

**Review by pirj — APPROVED** [review]
LGTM! Thank you!

**Comment by Darhazer** [comment]
Let's release 👍

**Review by ydah — APPROVED** [review]
🚀

**Comment by bquorning** [comment]
Let’s get #1666 merged first, then rebase this PR. I am unable to do the actual release for the next week or so, but feel free to do it without me.

**Comment by bquorning** [comment]
Ready for review. We’ll leave #1666 for the next release, I hope that’s ok with @ydah

**Review by ydah — APPROVED** [review]
We leave #1666 until the next release👍 
Let's proceed with the release 🚀

**Review by Darhazer — APPROVED** [review]
🚀

**Pull request merged**
