### PR TITLE
feat: support "match" assertions in `RSpec/Rails/MinitestAssertions`

### PR DESCRIPTION
**Pull request by G-Rath**
Related to #1485

______________________________________________________________________

Before submitting the PR make sure the following are checked:

- [x] Feature branch is up-to-date with `master` (if not - rebase it).
- [x] Squashed related commits together.
- [x] Added tests.
- [x] Updated documentation.
- [x] Added an entry to the `CHANGELOG.md` if the new code introduces user-observable changes.
- [x] The build (`bundle exec rake`) passes (be sure to run this locally, since it may produce updated documentation that you will need to commit).

If you have created a new cop:

- [x] ~Added the new cop to `config/default.yml`.~
- [x] ~The cop is configured as `Enabled: pending` in `config/default.yml`.~
- [x] ~The cop is configured as `Enabled: true` in `.rubocop.yml`.~
- [x] ~The cop documents examples of good and bad code.~
- [x] ~The tests assert both that bad code is reported and that good code is not reported.~
- [x] ~Set `VersionAdded: "<<next>>"` in `default/config.yml`.~

If you have modified an existing cop's configuration options:

- [x] ~Set `VersionChanged: "<<next>>"` in `config/default.yml`.~

### CODE REVIEW

**Comment by G-Rath** [comment]
I'm not sure why the documentation check is failing - it passes for me locally, and running `rake generate_cops_documentation` produces no changes:

```
rubocop-rspec on  support-assert-match via 💎 v2.7.6
❯ bundle exec rake confirm_config documentation_syntax_check confirm_documentation
Files:         139
Modules:        19 (    6 undocumented)
Classes:       143 (    0 undocumented)
Constants:     197 (  196 undocumented)
Attributes:      1 (    0 undocumented)
Methods:       362 (  278 undocumented)
 33.52% documented
* generated /home/jones/workspace/projects-oss/rubocop-rspec/docs/modules/ROOT/pages//cops_rspec.adoc
* generated /home/jones/workspace/projects-oss/rubocop-rspec/docs/modules/ROOT/pages//cops_rspec_capybara.adoc
* generated /home/jones/workspace/projects-oss/rubocop-rspec/docs/modules/ROOT/pages//cops_rspec_factorybot.adoc
* generated /home/jones/workspace/projects-oss/rubocop-rspec/docs/modules/ROOT/pages//cops_rspec_rails.adoc

rubocop-rspec on  support-assert-match via 💎 v2.7.6
❯ bundle exec rake generate_cops_documentation
Files:         139
Modules:        19 (    6 undocumented)
Classes:       143 (    0 undocumented)
Constants:     197 (  196 undocumented)
Attributes:      1 (    0 undocumented)
Methods:       362 (  278 undocumented)
 33.52% documented
* generated /home/jones/workspace/projects-oss/rubocop-rspec/docs/modules/ROOT/pages//cops_rspec.adoc
* generated /home/jones/workspace/projects-oss/rubocop-rspec/docs/modules/ROOT/pages//cops_rspec_capybara.adoc
* generated /home/jones/workspace/projects-oss/rubocop-rspec/docs/modules/ROOT/pages//cops_rspec_factorybot.adoc
* generated /home/jones/workspace/projects-oss/rubocop-rspec/docs/modules/ROOT/pages//cops_rspec_rails.adoc

rubocop-rspec on  support-assert-match via 💎 v2.7.6
❯ git status
On branch support-assert-match
Your branch is up to date with 'origin/support-assert-match'.

nothing to commit, working tree clean
```

**Comment by pirj** [comment]
Maybe add a git diff call with printout before failing doc diff check?

**Comment by G-Rath** [comment]
Ah it's because of https://github.com/rubocop/rubocop/pull/12551 and my locally ignored lock - I'll do a dedicated PR for that

**Comment by pirj** [comment]
We opted not to commit the lockfile

thanks for finding the culprit!

**Review by bquorning — APPROVED** [review]

**Review by ydah — APPROVED** [review]

**Pull request merged**
