### PR TITLE
Add configuration option `OnlyStaticConstants` to `RSpec/DescribedClass`

### PR DESCRIPTION
**Pull request by ydah**
Fix: https://github.com/rubocop/rubocop-rspec/issues/1741#issuecomment-1973221319
Fix: https://github.com/rubocop/rubocop-rspec/issues/1741#issuecomment-1973604382

______________________________________________________________________

Before submitting the PR make sure the following are checked:

- [x] Feature branch is up-to-date with `master` (if not - rebase it).
- [x] Squashed related commits together.
- [x] Added tests.
- [x] Updated documentation.
- [x] Added an entry to the `CHANGELOG.md` if the new code introduces user-observable changes.
- [x] The build (`bundle exec rake`) passes (be sure to run this locally, since it may produce updated documentation that you will need to commit).

### CODE REVIEW

**Review by bquorning — APPROVED** [review]

**Comment by bquorning** [comment]
@pirj, I would love to hear your opinion on this PR.

**Comment by pirj** [comment]
I see it as a code smell when constants of the class under test are referenced from its spec, at least in a way that #1741 describes.

In general, this option probably makes sense to avoid offences in examples that are less coupled with the class under test.

I don’t have experience turning on Sorbet for specs, so I can’t suggest anything on this front.

I don’t take the “our CI pipelines fail” [argument](https://github.com/rubocop/rubocop-rspec/issues/1741#issuecomment-1972784112) given that auto-correction doesn’t break the spec.

Personally, I don’t see why ‘described_class::MyException' is any different from ‘described_class::VERSION’, but I understand that some people may prefer to use different styles for them.

Again, personally I think ‘described_class’ was a mistake, and we it’s good to quote class names in the top-level example group’s description, and to use the full class name elsewhere in the spec, with no indirection.

**Comment by bquorning** [comment]
> Again, personally I think ‘described_class’ was a mistake, and we it’s good to quote class names in the top-level example group’s description, and to use the full class name elsewhere in the spec, with no indirection.

I don’t remember us having this discussion before. I’m not sure I find `described_class` to be _that_ useful either. Do you know why it’s even a feature in RSpec?

**Comment by pirj** [comment]
> why it’s even a feature in RSpec?

This I can’t remember, but there’s a funny story about the RSpec 3 release and `described_class`, also a nice compilation of quotes and opinions in a discussion below the description https://github.com/rubocop/rspec-style-guide/issues/104. Since most likely the `described_class` will stay in RSpec 4, the cop should remain in some form, too.

If it’s not a big maintenance overhead for us to provide our users with an optional … option to style their code the way they like, why not?

**Review by bquorning — APPROVED** [review]

**Pull request merged**
