### PR TITLE
Bump to v2.29.0

### PR DESCRIPTION
**Pull request by bquorning**
I’m eager to see if [the new publish.yml workflow](https://github.com/rubocop/rubocop-rspec/blob/master/.github/workflows/publish.yml) works correctly ✨

Should we include #1854 in this release? Others too?

______________________________________________________________________

Before submitting the PR make sure the following are checked:

- [x] Feature branch is up-to-date with `master` (if not - rebase it).
- [x] Squashed related commits together.
- [ ] ~Added tests.~
- [x] Updated documentation.
- [x] Added an entry to the `CHANGELOG.md` if the new code introduces user-observable changes.
- [x] The build (`bundle exec rake`) passes (be sure to run this locally, since it may produce updated documentation that you will need to commit).

### CODE REVIEW

**Comment by ydah** [comment]
#1854 looked good so I merged it! Let's rebase and release it 🎉.

**Review by ydah — APPROVED** [review]

**Comment by ydah** [comment]
@bquorning`RSpec/EmptyOutput` seems to be remain  `<<next>>` in default.yml

**Comment by ydah** [comment]
Uh. Its failing to push because of the branch rules:
https://github.com/rubocop/rubocop-rspec/actions/runs/8561970997/job/23464311900

```
Run sed -i 's/version:.*$/version: ~/' docs/antora.yml
[master 0b618c0] Switch docs version back
 1 file changed, 1 insertion(+), 1 deletion(-)
remote: error: GH006: Protected branch update failed for refs/heads/master.        
remote: error: 12 of 12 required status checks are expected.        
To https://github.com/rubocop/rubocop-rspec
 ! [remote rejected] master -> master (protected branch hook declined)
error: failed to push some refs to 'https://github.com/rubocop/rubocop-rspec'
```

**Comment by bquorning** [comment]
At least it’s the very last step that fails, so we still have the gem build/push, tagging and GH release creation happening.

Perhaps there is a way to let GHA write to `master` branch despite the branch protection rules. I have pushed the Antora config change manually for now.

**Pull request merged**
