### PR TITLE
Change to be inline disable for `RSpec/SpecFilePathFormat` like `RSpec/FilePath`

### PR DESCRIPTION
**Pull request by ydah**
Fix: https://github.com/rubocop/rubocop-rspec/issues/1720

______________________________________________________________________

Before submitting the PR make sure the following are checked:

- [x] Feature branch is up-to-date with `master` (if not - rebase it).
- [x] Squashed related commits together.
- [x] Added tests.
- [-] Updated documentation.
- [x] Added an entry to the `CHANGELOG.md` if the new code introduces user-observable changes.
- [x] The build (`bundle exec rake`) passes (be sure to run this locally, since it may produce updated documentation that you will need to commit).

### CODE REVIEW

**Comment by ydah** [comment]
@dgollahon How about this? Changed to match the behavior of `RSpec/FilePath`.

**Review by pirj — APPROVED** [review]
Thank you!

**Comment by bquorning** [comment]
I don’t see any inline disables in the spec. Am I missing something?

**Comment by pirj** [comment]
The problem was that with ‘add_global_offense’ it wasn’t possible to use inline disabling.

Though now when you ask this, I feel that it’s weird to inline disable this cop.

> blanket disables early in the file or when attached to the end of a RSpec.describe line. Either way worked for RSpec/FilePath.

But for the sake of continuity, it feels we are doing the right thing.

Would you guys agree to revert this and use ‘add_global_offense’ in 3.0.0?

**Comment by bquorning** [comment]
@dgollahon actually makes a good case for inline disables in https://github.com/rubocop/rubocop-rspec/issues/1720#issuecomment-1728521808

**Comment by pirj** [comment]
It makes sense to me.
There are still cases for config file disables, e.g. a directory, so one doesn’t have to inline disable each newly-added file.

The approach provided by this PR would allow both inline and config-based, so our users could use it to their preference.

Agree to keep it this way 👍

**Review by bquorning — APPROVED** [review]

**Pull request merged**
