### PR TITLE
Bump version to v2.26.0

### PR DESCRIPTION
**Pull request by bquorning**
I think it’s time for the first release of the year. Changes:

- Add new `RSpec/RedundantPredicateMatcher` cop. ([@ydah])
- Add new `RSpec/RemoveConst` cop. ([@swelther])
- Add support for correcting "it will" (future tense) for `RSpec/ExampleWording`. ([@jdufresne])
- Add support for `symbol` style for `RSpec/SharedExamples`. ([@jessieay])
- Ensure `PendingWithoutReason` can detect violations inside shared groups. ([@robinaugh])

______________________________________________________________________

Before submitting the PR make sure the following are checked:

- [x] Feature branch is up-to-date with `master` (if not - rebase it).
- [x] Squashed related commits together.
- [ ] Added tests.
- [x] Updated documentation.
- [x] Added an entry to the `CHANGELOG.md` if the new code introduces user-observable changes.
- [x] The build (`bundle exec rake`) passes (be sure to run this locally, since it may produce updated documentation that you will need to commit).

[@ydah]: https://github.com/ydah
[@swelther]: https://github.com/swelther
[@jdufresne]: https://github.com/jdufresne
[@jessieay]: https://github.com/jessieay
[@robinaugh]: https://github.com/robinaugh

### CODE REVIEW

**Comment by bquorning** [comment]
Maybe we can still add #1722 to this release?

**Comment by ydah** [comment]
> Maybe we can still add https://github.com/rubocop/rubocop-rspec/pull/1722 to this release?

IMO we can still add. @pirj what do you think?

**Review by ydah — APPROVED** [review]

**Comment by bquorning** [comment]
I left a few comments on #1722.

**Comment by pirj** [comment]
No objections to #1722

**Pull request merged**
