### PR TITLE
Fix bug with range in RepeatedIncludeExample cop

### PR DESCRIPTION
**Pull request by hasghari**
Fixes issue #1866 

______________________________________________________________________

Before submitting the PR make sure the following are checked:

- [x] Feature branch is up-to-date with `master` (if not - rebase it).
- [x] Squashed related commits together.
- [x] Added tests.
- [ ] Updated documentation.
- [x] Added an entry to the `CHANGELOG.md` if the new code introduces user-observable changes.
- [x] The build (`bundle exec rake`) passes (be sure to run this locally, since it may produce updated documentation that you will need to commit).

### CODE REVIEW

**Review by bquorning — APPROVED** [review]

**Review by ydah — COMMENTED** [review]
Could you add an entry to the `CHANGELOG.md` ?

**Review by ydah — COMMENTED** [review]
It looks failed for rspec. Could you fixes failed tests?

**Comment by bquorning** [comment]
If you run `bundle exec rake` locally, it will tell you what to do (hint: put a link to your GitHub profile at the bottom of Changelog)

**Comment by bquorning** [comment]
@ydah Do you know why mdformat is failing?

**Comment by hasghari** [comment]
Thanks for the tip, I've fixed the changelog.

**Review by bquorning — APPROVED** [review]

**Pull request merged**
