### PR TITLE
Add missing documentation for `single_statement_only` style of `RSpec/ImplicitSubject` cop

### PR DESCRIPTION
**Pull request by tejasbubane**
---

Before submitting the PR make sure the following are checked:

* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [ ] Added tests.
* [x] Updated documentation.
* [x] Added an entry to the `CHANGELOG.md` if the new code introduces user-observable changes.
* [x] The build (`bundle exec rake`) passes (be sure to run this locally, since it may produce updated documentation that you will need to commit).

If you have created a new cop:

* [ ] Added the new cop to `config/default.yml`.
* [ ] The cop is configured as `Enabled: pending` in `config/default.yml`.
* [ ] The cop documents examples of good and bad code.
* [ ] The tests assert both that bad code is reported and that good code is not reported.
* [ ] Set `VersionAdded` in `default/config.yml` to the next minor version.

If you have modified an existing cop's configuration options:

* [ ] Set `VersionChanged` in `config/default.yml` to the next major version.

### CODE REVIEW

**Comment by tejasbubane** [comment]
CI failure from master fixed in https://github.com/rubocop/rubocop-rspec/pull/1154

**Comment by pirj** [comment]
Apart from internal affairs, you have to run `rake generate_cops_documentation`.

**Comment by tejasbubane** [comment]
@pirj CI fixed.

**Comment by pirj** [comment]
Thanks!

**Pull request merged**
