### PR TITLE
Update RSpec 4 CI to the monorepo

### PR DESCRIPTION
**Pull request by Earlopain**
Also see https://github.com/rubocop/rubocop/pull/13576

______________________________________________________________________

Before submitting the PR make sure the following are checked:

- [x] Feature branch is up-to-date with `master` (if not - rebase it).
- [x] Squashed related commits together.
- [ ] Added tests.
- [ ] Updated documentation.
- [ ] Added an entry to the `CHANGELOG.md` if the new code introduces user-observable changes.
- [ ] The build (`bundle exec rake`) passes (be sure to run this locally, since it may produce updated documentation that you will need to commit).

### CODE REVIEW

**Review by bquorning — APPROVED** [review]

**Comment by pirj** [comment]
Thank you!

Please let me do a quick sanity check, since it's not obvious at all from the CI job which RSpec version was installed apart from
```
Removing rspec (3.13.0)
```
which is not indicative.

I intend to:
1. Remove some clamp around old-fashioned code that makes RSpec 4 to break
2. Observe the RSpec 4 CI job to fail
3. Revert the commit
...
4. Merge!

**Comment by pirj** [comment]
[Failed](https://github.com/rubocop/rubocop-rspec/actions/runs/12296181627/job/34314661009?pr=2006) as expected:
```
undefined method `it_should_behave_like' for class RSpec::ExampleGroups::Weirdness
```
My apologies for being extra cautious, and thanks once again!

**Comment by pirj** [comment]
@bquorning Can you merge without Mdformat passing? I recall there was a checkbox to merge anyway, but most probably in rspec-factory_bot.

@ydah Do you have an idea what README.md does it complain about?

**Comment by bquorning** [comment]
Yep, I’ll force-merge this one. We will fix mdformat in another PR.

**Pull request merged**
