### PR TITLE
Bump version to v2.20.0

### PR DESCRIPTION
**Pull request by bquorning**
Should we push a ~bugfix~ minor release?

______________________________________________________________________

Before submitting the PR make sure the following are checked:

- [x] Feature branch is up-to-date with `master` (if not - rebase it).
- [x] Squashed related commits together.
- [ ] Added tests.
- [x] Updated documentation.
- [x] Added an entry to the `CHANGELOG.md` if the new code introduces user-observable changes.
- [x] The build (`bundle exec rake`) passes (be sure to run this locally, since it may produce updated documentation that you will need to commit).

### CODE REVIEW

**Comment by pirj** [comment]
I apologize for the late appearance, I have some doubts regarding [this change](https://github.com/rubocop/rubocop-rspec/pull/1598/files#r1134657996).

**Comment by ydah** [comment]
@bquorning @pirj Sorry for the delay in responding. I have opened a revised proposal on the matter as a PR. Please give me your feedback.
- https://github.com/rubocop/rubocop-rspec/pull/1603

**Comment by bquorning** [comment]
@pirj Does https://github.com/rubocop/rubocop-rspec/pull/1604 address your concerns?

**Comment by ydah** [comment]
@pirj @bquorning @Darhazer Sorry to bother you, but we would like to decide on a response plan and include it in the release.

**Comment by ydah** [comment]
@bquorning @pirj 
I believe this has probably resolved the blockers for the release. Please let me know if I have missed anything.
The following PR is closed.
- https://github.com/rubocop/rubocop-rspec/pull/1603#issuecomment-1507082570

**Comment by pirj** [comment]
No objections to releasing what we have.

**Comment by bquorning** [comment]
I have updated this PR to now cut a minor release (v2.20.0). Are there any more pull requests we should merge for this release?

**Comment by ydah** [comment]
I think the following PR looks good to merge for this release.
- https://github.com/rubocop/rubocop-rspec/pull/1618

**Comment by ydah** [comment]
@bquorning @pirj @Darhazer 
I would like to extract the RuboCop FactoryBot for the v2.21.0 release. WDYT?

**Comment by bquorning** [comment]
cc @rubocop/rubocop-rspec

**Comment by pirj** [comment]
#1610 and #1574 look solid.
#1527 is fine too, just needs a rebase. I never got to `rubocop-rspec-rails` extraction, so it doesn't make sense to keep holding it off.

**Comment by pirj** [comment]
All for the FactoryBot extraction in 2.21.0 🙌

**Comment by ydah** [comment]
The test that is now failing in CI / Edge RuboCop: spec will also succeed with https://github.com/rubocop/rubocop-rspec/pull/1620

**Comment by pirj** [comment]
#1619 is a small one, now green thanks to #1620.

**Comment by bquorning** [comment]
Thanks for the feedback, I have updated this PR after merging the suggested PRs:

- #1527 
- #1574
- #1610 
- #1619 
- #1620 

I also tried reordering the changelog entry for this release, to closer resemble what is recommended by https://keepachangelog.com/en/1.0.0/ (“The same types of changes should be grouped” they say, and list “Types of changes” as Added, Changed, Deprecated, Removed, Fixed, Security)

**Review by pirj — APPROVED** [review]
Thank you! 🙌 
🚢

**Pull request merged**
