### PR TITLE
`AutoCorrect: contextual` needs rubocop v1.61

### PR DESCRIPTION
**Pull request by ydah**
https://github.com/rubocop/rubocop/releases/tag/v1.61.0

______________________________________________________________________

Before submitting the PR make sure the following are checked:

- [x] Feature branch is up-to-date with `master` (if not - rebase it).
- [x] Squashed related commits together.
- [-] Added tests.
- [-] Updated documentation.
- [-] Added an entry to the `CHANGELOG.md` if the new code introduces user-observable changes.
- [x] The build (`bundle exec rake`) passes (be sure to run this locally, since it may produce updated documentation that you will need to commit).

### CODE REVIEW

**Comment by pirj** [comment]
The is is a big jump
Can we make it together with the 3.0 release, or in 3.x?

How did you catch this?
I see that https://github.com/rubocop/rubocop-rspec_rails/commit/ff9bf2a24a4157cd58c51c92f8e31a98571c69cc is :x:, but I don’t see why.
 Do we have this build job that checks with the lowest supported rubocop version?

**Comment by bquorning** [comment]
This makes me a bit hesitant to backport our contextual autocorrection to 2-x-stable.

**Comment by bquorning** [comment]
> Do we have this build job that checks with the lowest supported rubocop version?

That would be https://github.com/rubocop/rubocop-rspec/actions/runs/9355023880/job/25749240673, using `gem 'rubocop', '= 1.40'` on e49f221245f8e23fd1167677f6557623d9d702ce.

**Comment by bquorning** [comment]
> I see that [rubocop/rubocop-rspec_rails@ff9bf2a](https://github.com/rubocop/rubocop-rspec_rails/commit/ff9bf2a24a4157cd58c51c92f8e31a98571c69cc) is ❌, but I don’t see why.

The failing CI is because https://github.com/rubocop/rubocop-rspec_rails/pull/30 is not (and cannot be) merged yet.

**Comment by bquorning** [comment]
I’m trying to read https://github.com/rubocop/rubocop/pull/12657 and I _think_ if people are using an older version of RuboCop than v1.61, autocorrect will just keep working as it always has. But if they’re using v1.61+ then they get the new LSP feature too.

In conclusion, I don’t think we _need_ this PR. People who want to use LSP should use RuboCop v1.61+ anyway. But on the other hand, the target branch is `master` which is targeted at our v3.0, and we can decide to _not_ backport to `2-x-stable`, right?

**Comment by ydah** [comment]
@bquorning Thanks for catching that. You're right, it is indeed. I'm going to close this PR since there is no need to necessarily update version it.

**Comment by bquorning** [comment]
Yeah, maybe we should have merged this before v3.0.0.
Reopening the PR as maybe we want to do it as a bugfix in v3.0.1?

**Comment by ydah** [comment]
Let's do that. @pirj WDYT?

**Comment by bquorning** [comment]
I added one commit, so that merging this PR will release v3.0.1.

I feel like I have been a little too eager to merge and release lately, so I’ll wait for @pirj to review before merging.

**Comment by pirj** [comment]
Let’s merge and release as 3.0.1, i see no big harm here.

The only problem would be people doing `bundle update —conservative rubocop-rspec`, which would resolve to 3.0.0 as 3.0.1 would depend on newer rubocop and won’t match.

I’d be most interested in why our CI “oldest rubocop” job didn’t catch this.

**Comment by ydah** [comment]
In the following sections, if AutoCorrect was set to a value other than boolean, the corresponding error message was output, so it was necessary to update to v1.61. So, let's change it and release it.

https://github.com/rubocop/rubocop/blob/edb56c927d4d1112a9c02990da31767e68d2121c/lib/rubocop/config_validator.rb#L251-L268

**Pull request merged**
