### PR TITLE
Release v3.2.0

### PR DESCRIPTION
**Pull request by ydah**
It has been a month since the last release. It is time to move on to the next version.

______________________________________________________________________

Before submitting the PR make sure the following are checked:

- [x] Feature branch is up-to-date with `master` (if not - rebase it).
- [x] Squashed related commits together.
- [-] Added tests.
- [-] Updated documentation.
- [-] Added an entry to the `CHANGELOG.md` if the new code introduces user-observable changes.
- [x] The build (`bundle exec rake`) passes (be sure to run this locally, since it may produce updated documentation that you will need to commit).

### CODE REVIEW

**Review by pirj — APPROVED** [review]
Thank you!

**Comment by bquorning** [comment]
I would have liked #1968 to be merged first. Oh well, we’ll have it in v3.3.0 then 😬

**Comment by ydah** [comment]
@bquorning Oops, sorry.

**Comment by bquorning** [comment]
No worries.

**Pull request merged**
