### PR TITLE
Use rubocop/rubocop-rspec instead of rubocop-hq/rubocop-rspec

### PR DESCRIPTION
**Pull request by ydah**
This PR is use rubocop/rubocop-rspec instead of rubocop-hq/rubocop-rspec in README

______________________________________________________________________

Before submitting the PR make sure the following are checked:

- [x] Feature branch is up-to-date with `master` (if not - rebase it).
- [x] Squashed related commits together.
- [-] Added tests.
- [-] Updated documentation.
- [-] Added an entry to the `CHANGELOG.md` if the new code introduces user-observable changes.
- [x] The build (`bundle exec rake`) passes (be sure to run this locally, since it may produce updated documentation that you will need to commit).

### CODE REVIEW

**Comment by ydah** [comment]
Aah! I see. It looks like the following correspondence will need to be incorporated after the merge
- https://github.com/rubocop/rubocop-rspec/pull/1525

**Comment by pirj** [comment]
Merged #1525. Can you please try again?

**Comment by pirj** [comment]
Thank you! 🙌

**Comment by ydah** [comment]
Thank you very much 😄

**Pull request merged**
